import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypeScript,
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "next-env.d.ts",
      // Windows self-host build output (bundled standalone app + tools + vendored
      // node/postgres). Gitignored and regenerated by scripts/package-windows.mjs;
      // never lint these thousands of third-party/compiled files.
      "packaging/windows/dist/**",
    ],
  },
];

export default eslintConfig;
